#!/bin/bash
# update-newspaper-shortcuts.sh — make the current Default shortcut set the
# built-in "Newspaper Default".
#
# "Newspaper Default" is this build's compiled-in shortcuts with
# resources/keysets/malayalam-dtp.xml laid over them
# (Prefs_KeyboardShortcuts::buildSetKeys). This script rewrites that file from
# the set currently marked Default in Preferences › Keyboard Shortcuts, so a
# full set here gives every action exactly the key the Default set has.
#
# Usage:
#   tools/update-newspaper-shortcuts.sh            # rewrite the keyset only
#   tools/update-newspaper-shortcuts.sh --deb      # ...then rebuild, install, build the .deb
#
# Reads from the profile of the desktop user (default /home/s1); override with
#   SCRIBUS_PROFILE=/path/to/.config/scribus
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
PROFILE=${SCRIBUS_PROFILE:-/home/s1/.config/scribus}
OUT="$REPO/resources/keysets/malayalam-dtp.xml"

name=$(grep -o 'default_set" value="[^"]*"' "$PROFILE/prefs172.xml" | head -1 | cut -d'"' -f3) || true
if [ -z "$name" ]; then
	echo "No Default shortcut set is chosen in $PROFILE/prefs172.xml." >&2
	echo "Pick one in Preferences › Keyboard Shortcuts › Set as Default first." >&2
	exit 1
fi

# Find the user set whose <shortcutset name="..."> is the Default.
src=""
for f in "$PROFILE"/shortcut-sets/*.xml; do
	[ -e "$f" ] || continue
	if grep -q "<shortcutset name=\"$name\"" "$f"; then src=$f; break; fi
done
if [ -z "$src" ]; then
	echo "The Default set \"$name\" is not one of your own sets in $PROFILE/shortcut-sets/." >&2
	echo "(A built-in Default has nothing new to copy.)" >&2
	exit 1
fi

{
	echo '<?xml version="1.0" encoding="UTF-8"?>'
	echo '<!--'
	echo '  "Newspaper Default" keyboard shortcut set.'
	echo ''
	echo "  Generated by tools/update-newspaper-shortcuts.sh from the user set \"$name\""
	echo "  on $(date +%Y-%m-%d). Edit shortcuts in Scribus and re-run the script"
	echo '  rather than editing this file by hand.'
	echo ''
	echo '  Laid over the compiled-in defaults: every action listed here gets exactly'
	echo '  this key (shortcut="" means none); actions added to Scribus later, and so'
	echo '  missing here, keep their compiled-in default.'
	echo '-->'
	echo '<shortcutset name="Newspaper Default">'
	grep '<function ' "$src"
	echo '</shortcutset>'
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"

count=$(grep -c '<function ' "$OUT")
keyed=$(grep '<function ' "$OUT" | grep -vc 'shortcut=""' || true)
echo "Wrote $OUT from \"$name\" ($src): $count actions, $keyed with a key."

if [ "${1:-}" = "--deb" ]; then
	cd "$REPO"
	cmake --build build -j"$(nproc)"
	cmake --install build
	version="1.7.3-$(date +%d%m%y)"
	(cd build && cpack -G DEB \
		-D CPACK_PACKAGE_VERSION="$version" \
		-D CPACK_DEBIAN_PACKAGE_RELEASE=1 \
		-D CPACK_DEBIAN_FILE_NAME=DEB-DEFAULT)
	deb="$REPO/build/scribus_${version}-1_amd64.deb"
	echo "Package: $deb"
	dpkg -c "$deb" | grep 'keysets/malayalam-dtp.xml'
fi
