install(FILES
faircode-frames/QuoteA.sce
faircode-frames/QuoteA.png
faircode-frames/QuoteB.sce
faircode-frames/QuoteB.png
faircode-frames/TitleBox.sce
faircode-frames/TitleBox.png
faircode-frames/TintedBox.sce
faircode-frames/TintedBox.png
faircode-frames/CalloutL.sce
faircode-frames/CalloutL.png
faircode-frames/CalloutR.sce
faircode-frames/CalloutR.png
faircode-frames/AngledBar.sce
faircode-frames/AngledBar.png
faircode-frames/Brackets.sce
faircode-frames/Brackets.png
DESTINATION ${SHAREDIR}scrapbook/faircode-frames
)
